[package]
name = "sippin-soda-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
sippin-soda-engine = { path = "../crates/engine" }
serde = { version = "1", features = ["derive"] }
base64 = "0.22"
tokio = { version = "1", features = ["time", "net", "io-util", "macros", "rt-multi-thread"] }
